"""empty message

Revision ID: 8f0b5af4db2c
Revises: ee90c794f437
Create Date: 2025-07-24 19:42:13.611070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0b5af4db2c'
down_revision = 'ee90c794f437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.drop_column('localitation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localitation', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
