"""empty message

Revision ID: f68ec5771f1a
Revises: ee90c794f437
Create Date: 2025-07-26 08:53:14.445375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68ec5771f1a'
down_revision = 'ee90c794f437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('was_sold', sa.Boolean(), nullable=True))
        batch_op.drop_column('localitation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localitation', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('was_sold')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
